version: '3.8'

services:
  postservice:
      build: ..
      container_name: postservice
      ports:
        - "8090:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/messages
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: secret
      depends_on:
        - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: messages
    ports:
      - "3306:3306"
